# Pandas Data Frame API

### In general, you could say that the Pandas data frame consists of three main components: the data, the index, and the columns.

##### Structured arrays example

In [6]:
import numpy as np
my_array = np.ones(3, dtype=([('foo', int), ('bar', float)]))
print(my_array['foo'])
print(my_array['bar'])

[1 1 1]
[ 1.  1.  1.]


##### Create a Pandas DataFrame using numpy 

In [24]:
data = np.array([['','Col1','Col2'],
                ['Row1',1,2],
                ['Row2',3,4]])
print(data)

[['' 'Col1' 'Col2']
 ['Row1' '1' '2']
 ['Row2' '3' '4']]


In [25]:
my_2darray = np.array([[1, 2, 3], [4, 5, 6]])
print(my_2darray)

my_dict = {1: ['1', '3'], 2: ['1', '2'], 3: ['2', '4']}
print(my_dict)

[[1 2 3]
 [4 5 6]]
{1: ['1', '3'], 2: ['1', '2'], 3: ['2', '4']}


##### Creating Pandas Data Frame using Pandas Data Frame Functions

In [23]:
import pandas as pd
print(pd.DataFrame(data=data[1:,1:],
                  index=data[1:,0],
                  columns=data[0,1:]))

     Col1 Col2
Row1    1    2
Row2    3    4


In [14]:
my_df = pd.DataFrame(data=[4,5,6,7], index=range(0,4), columns=['A'])
print(my_df)

my_series = pd.Series({"Belgium":"Brussels", "India":"New Delhi", "United Kingdom":"London", "United States":"Washington"})
print(my_series)

Belgium             Brussels
India              New Delhi
United Kingdom        London
United States     Washington
dtype: object


In [20]:
df = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6]]))
print(df)
print(len(df), " is length of df")
print(df[0].count() , " df[].count")

   0  1  2
0  1  2  3
1  4  5  6
2  is length of df
2  df[].count


##### Accessing Values in Pandas

In [45]:
df = pd.Series({"Belgium":"Brussels", "India":"New Delhi", "United Kingdom":"London", "United States":"Washington"})


# Using `iloc[]`
print(df.iloc[0])

# Using `loc[]`
print(df.loc['India'])

# Using `at[]`
print(df.at['United Kingdom'])

# Using `iat[]`
print(df.iat[3])

# Using `get_value(index, column)`
print(df.get_value('Belgium'))

Brussels
New Delhi
London
Washington
Brussels


In [46]:
df = pd.DataFrame(data=[4,5,6,7], index=range(0,4), columns=['A'])

# Using `iloc[]`
print(df.iloc[0][0])

# Using `loc[]`
print(df.loc[0]['A'])

# Using `at[]`
print(df.at[0,'A'])

# Using `iat[]`
print(df.iat[0,0])

# Using `get_value(index, column)`
print(df.get_value(0, 'A'))

4
4
4
4
4


In [56]:
# Use `iloc[]` to select row `0`
print(df.iloc[0])
 

A    4
Name: 0, dtype: int64
